### ISSUE TITLE
fail on up docker

### ISSUE THREAD

**Issue by kewogc** [otiai10/webm2mp4#1]
`
$ docker-compose up
Building web
Step 1/8 : FROM golang:1.8
1.8: Pulling from library/golang
4176fe04cefe: Pull complete
851356ecf618: Pull complete
6115379c7b49: Pull complete
69914558965c: Pull complete
b108f9aa98db: Pull complete
df7abcd2981e: Pull complete
3e60cb3f592b: Pull complete
Digest: sha256:f0b5dab7581eddb49dabd1d1b9aa505ca3edcdf79a66395b5bfa4f3c036b49ef
Status: Downloaded newer image for golang:1.8
 ---> 0d283eb41a92
Step 2/8 : MAINTAINER otiai10 <otiai10@gmail.com>
 ---> Running in 8fe317392786
Removing intermediate container 8fe317392786
 ---> 7d74221ec71c
Step 3/8 : RUN apt-get -qq update
 ---> Running in 8c8cdc1c400d
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get -qq update' returned a non-zero code: 100
`

**Comment by otiai10** [comment]
Thanks! It's reproducible. I will fix

**Comment by otiai10** [comment]
@kewogc Just pushed the fix. Because I don't have webm file to be tested, could you please have quick check with current version of Dockerfile? Don't forget to add `--build` flag for `docker-compose` ;)

Thanks
